version: "2.4"

services:
  axonserver:
    hostname: axonserver
    user: root
    container_name: axonserver-scsc
    restart: always
    image: axoniq/axonserver:2023.1.1-jdk-17-dev
    environment:
      - AXONIQ_LICENSE=/axonserver/config/axoniq.license
      - LOCAL_AXONSERVER=axonserver
    ports:
      - "8024:8024"
      - "8124:8124"
      - "8224:8224"
    volumes:
      - axoniq_data:/axonserver/data:rw
    healthcheck:
      test: curl -f http://localhost:8024/actuator/health || exit 1;
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    hostname: postgres
    image: postgres:bullseye
    command: postgres -c 'max_connections=200'
    container_name: postgres-scsc
    restart: always
    environment:
      - POSTGRES_DB=scsc
      - PGUSER=scsc
      - POSTGRES_USER=scsc
      - POSTGRES_PASSWORD=scsc
    ports:
      - "5432:5432"
    healthcheck:
      test: "pg_isready"
      interval: 5s
      timeout: 10s
      retries: 3

#  scsc:
#    hostname: scsc
#    container_name: scsc
#    restart: always
#    environment:
#      - AXON_AXONSERVER_SERVERS=axonserver
#      - AXON_AXONSERVER_CONTEXT=default
#      - POSTGRES_URL=jdbc:postgresql://postgres/scsc
#    build:
#      dockerfile: ../docker/Dockerfile_scsc
#    depends_on:
#      axonserver:
#        condition: service_healthy
#
#  warehouse:
#    hostname: warehouse
#    container_name: warehouse
#    restart: always
#    environment:
#      - AXON_AXONSERVER_SERVERS=axonserver
#      - AXON_AXONSERVER_CONTEXT=default
#      - POSTGRES_URL=jdbc:postgresql://postgres/scsc
#    ports:
#      - "8080:8081"
#    build:
#      dockerfile: ./docker/Dockerfile_warehouse
#    depends_on:
#      axonserver:
#        condition: service_healthy
#
#  inventory:
#    hostname: inventory
#    container_name: inventory
#    restart: always
#    environment:
#      - AXON_AXONSERVER_SERVERS=axonserver
#      - AXON_AXONSERVER_CONTEXT=default
#      - POSTGRES_URL=jdbc:postgresql://postgres/scsc
#    ports:
#      - "8081:8082"
#    build:
#      dockerfile: ../docker/Dockerfile_inventory
#    depends_on:
#      axonserver:
#        condition: service_healthy
#

volumes:
  axoniq_data:
